project:
  type: website
  output-dir: docs

website:
  title: "Hopetopia"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Mayor"
        file: mayor.qmd
      - text: "Emergency Services"
        file: des.qmd
      - text: "Community Development"
        file: dcd.qmd
      - text: "Social Services"
        file: dss.qmd
      - text: "General Services"
        file: dgs.qmd
      - text: "Education"
        file: ed.qmd
      
    background: success
  
  sidebar:
    - title: "Home"
      style: "docked"
      search: true
      contents:
        - section: "Our People"
          contents:
            - href: people.qmd
        - section: "Our Wards"
          contents:
            - href: wards.qmd
        - section: "Our Economy"
          contents: 
            - href: econ.qmd
            
    - title: "Office of the Mayor"
      contents: 
            - href: abtmayor.qmd
            - href: mayorbudget.qmd
    
    - title: "Emergency Services"
      contents:
        - section: "Police Department"
          contents:
            - href: aboutpd.qmd
            - href: budgetpd.qmd
        - section: "Fire Department"
          contents:
            - href: aboutfd.qmd
            - href: budgetfd.qmd
    
    - title: "Community Development"
      contents:
        - section: "Housing and Planning"
          contents:
            - href: abouthp.qmd
            - href: budgethp.qmd
        - section: "Buidings and Regulations"
          contents:
            - href: aboutbr.qmd
            - href: budgetbr.qmd
          
    - title: "Social Services"
      contents:
        - section: "Adult Services"
          contents:
            - href: aboutas.qmd
            - href: budgetas.qmd
        - section: "Youth Services"
          contents:
            - href: aboutys.qmd
            - href: budgetys.qmd
    
    - title: "General Services"
      contents:
        - section: "Transportation"
          contents:
            - href: abouttd.qmd
            - href: budgettd.qmd
        - section: "General Services"
          contents:
            - href: aboutgs.qmd
            - href: budgetgs.qmd
            
    - title: "Education"
      contents:
        - section: Public Schools
          contents:
            - href: aboutps.qmd
            - href: budgetps.qmd
        - section: Evaluation
          contents:
            - href: aboutev.qmd
            - href: budgetev.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

