project:
  type: website
  output-dir: docs

website:
  title: "Hopetopia"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Mayor"
        file: mayor.qmd
      - text: "Emergency Services"
        file: des.qmd
      - text: "Community Development"
        file: dcd.qmd
      - text: "Social Services"
        file: dss.qmd
      - text: "General Services"
        file: dgs.qmd
      - text: "Education"
        file: ed.qmd
      
    background: success
  
  sidebar:
    - title: "Home"
      style: "docked"
      search: true
      contents:
        - section: "Our People"
          contents:
            - people.qmd
        - section: "Our Wards"
          contents:
            - wards.qmd
        - section: "Our Economy"
          contents: 
            - econ.qmd
            
    - title: "Office of the Mayor"
      contents: 
            - abtmayor.qmd
            - mayorbudget.qmd
    
    - title: "Emergency Services"
      contents:
        - section: "Police Department"
          contents:
            - aboutpd.qmd
            - budgetpd.qmd
        - section: "Fire Department"
          contents:
            - aboutfd.qmd
            - budgetfd.qmd
    
    - title: "Community Development"
      contents:
        - section: "Housing and Planning"
          contents:
            - abouthp.qmd
            - budgethp.qmd
        - section: "Buidings and Regulations"
          contents:
            - aboutbr.qmd
            - budgetbr.qmd
          
    - title: "Social Services"
      contents:
        - section: "Adult Services"
          contents:
            - aboutas.qmd
            - budgetas.qmd
        - section: "Youth Services"
          contents:
            - aboutys.qmd
            - budgetys.qmd
    
    - title: "General Services"
      contents:
        - section: "Transportation"
          contents:
            - abouttd.qmd
            - budgettd.qmd
        - section: "General Services"
          contents:
            - aboutgs.qmd
            - budgetgs.qmd
            
    - title: "Education"
      contents:
        - section: Public Schools
          contents:
            - aboutps.qmd
            - budgetps.qmd
        - section: Evaluation
          contents:
            - aboutev.qmd
            - budgetev.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

