project:
  type: website
  output-dir: docs

website:
  title: "Hopetopia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    background: success
  
  sidebar:
    - title: "About"
      style: "docked"
      search: true
      contents:
        - section: "Our People"
          contents:
            - index.qmd
            
        - section: "Our Wards"
          contents:
            - index.qmd
        
        - section: "Our Economy"
          contents: 
            - index.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

