project:
  type: website
  output-dir: docs

website:
  title: "Hopetopia"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Mayor"
        file: mayor.qmd
      - text: "Emergency Services"
        file: des.qmd
      - text: "Community Development"
        file: dcd.qmd
      - text: "Social Services"
        file: dss.qmd
      - text: "General Services"
        file: dgs.qmd
      - text: "Education"
        file: ed.qmd
      
    background: success
  
  sidebar:
    - title: "Home"
      style: "docked"
      search: true
      contents:
        - section: "Our City"
          contents:
            - href: people.qmd
            - href: wards.qmd
            - href: econ.qmd
            
        - section: "Office of the Mayor"
          contents: 
            - href: mayor.qmd
            - href: mayorbudget.qmd
    
        - section: "Emergency Services"
          contents:
            - href: des.qmd
            - href: aboutpd.qmd
            - href: budgetpd.qmd
            - href: aboutfd.qmd
            - href: budgetfd.qmd
    
        - section: "Community Development"
          contents:
            - href: dcd.qmd
            - href: abouthp.qmd
            - href: budgethp.qmd
            - href: aboutbr.qmd
            - href: budgetbr.qmd
          
        - section: "Social Services"
          contents:
            - href: dss.qmd
            - href: aboutas.qmd
            - href: budgetas.qmd
            - href: aboutys.qmd
            - href: budgetys.qmd
    
        - section: "General Services"
          contents:
            - href: dgs.qmd
            - href: abouttd.qmd
            - href: budgettd.qmd
            - href: aboutgs.qmd
            - href: budgetgs.qmd
            
        - section: "Education"
          contents:
            - href: ed.qmd
            - href: aboutps.qmd
            - href: budgetps.qmd
            - href: aboutev.qmd
            - href: budgetev.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

