project:
  type: website
  output-dir: docs

website:
  title: "Hopetopia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    background: success

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

