---
title: "Transportation Department"
---

## Mission Statement

The Mission of the Hopetopia Transportation
Department is to ensure our citizens and goods have the safest way of transportation. We also want to establish that all of our citizens are going to their place of work, school, etc. in a timely and efficient manner. The Transportation Department is committed to expanding our public transportation use to lessen the waste that Hopetopia contributes into the atmosphere. We would also want to make sure that the transportation for all citizens in Hopetopia has roads, bridges, and sidewalks that are up to safety regulations. Overall we would like for their transportation experience to make them feel safe both inside the public vehicle and with the vehicle itself.

## Recent Events

::: callout-note
**10/3/2023** In conjunction with city-wide efforts to improve services, the Transportation Department has identified three performance goals that it will begin tracking and reporting publicly. 1. Ensuring an on-time bus system throughout the city. 2. Piloting a free-bus program and studying growth in ridership (current Friday ridership averages 19,000). 3. Safer streets for all modes through faster pothole repair (currently, the 60 potholes per month reported in each ward are fixed on average 3 weeks after the first report).
:::

::: callout-note
**9/27/2023** The Transportation Department operates an extensive city-wide bus system as well as maintaining the roads and approving the design and construction of new roads and bridges. In recent years, cuts have made operating the bus system difficult. Two years ago, you had to reduce the number of busses on routes in the NW and SE quadrants. The service reductions have led to complaints of wait times as high as 60 minutes in those quadrants and you have seen a decline 10% decline in ridership city wide. The biggest ridership declines have come from the NE quadrant, though the reason is unclear. You've also been receiving a variety of complaints about road quality and streetlight outages in the NW quadrant.
:::

## Operations

### Who We Are

@tbl-tdstaff summarizes the demographic characteristics of our employees overall and by position.

|                 | Central Office | Drivers | Construction and Maintenance | Field Office | Total |
|------------|:----------:|:----------:|:----------:|:----------:|:----------:|
| White           |      464       |   928   |             696              |     290      | 2,377 |
| Non-white       |      116       |   812   |             464              |     232      | 1,623 |
| Male            |      232       |   754   |             812              |     174      | 1,971 |
| Female          |      348       |   986   |             348              |     348      | 1,913 |
| Non-resident    |      174       |   696   |             812              |     174      | 1,681 |
| College degree+ |      464       |   870   |             232              |     406      | 3,594 |
| Total           |      580       |  1,739  |            1,159             |     522      | 4,000 |

: : Transportation Department Staffing Descriptive Statistics (FTE) {#tbl-tdstaff}

### How We're Doing

@tbl-tdperf provides an overview of our performance indicators for each of our goals for the year by ward. We operate 1,200 bus routes throughout the city and each ward sees between 6,000 and 10,000 trips along 300-400 routes per day.

|                                                    | NW    | SW  | NE  | SE    |
|----------------------------------------------------|-------|-----|-----|-------|
| Number of buses > 5 mins late on route  (per month)   | 2,250 | 836 | 236 | 1,504 |
| Number of Friday Trips (per month) | 600    | 7,500  | 11,000  | 580    |
| Number of potholes patched within 1 week of first report | 6     | 12  | 8   | 3     |

: Transportation Department Performance Indicators by Ward {#tbl-tdperf}


## Current Operations Budget

@tbl-tdbudget23 summarizes our FY23 operations budget. After our initial informational town hall and meetings with leaders from the Neighborhood Associations, college representatives from local colleges, and the Hopetopia Chamber of Commerce, we have decided to prioritize expanding bus service and increasing the frequency of service on existing routes of HOPBUS services in the coming year and invest more in bridge and road repair.

::: {#tbl-tdbudget23 layout-ncol="2"}
| Transportation Department      | 625,885 |
|--------------------------------|---------|
| Traffic engineering and design | 87,645  |
| Route construction             | 189,535 |
| Fleet                          | 55,901  |
| Bus operations                 | 150,000 |
| Management                     | 59,622  |
| Maintenance                    | 83,180  |

: Transportation Department Operations (in 1,000s) {#tbl-tdops23}

| Transportation Department | 625,885 |
|---------------------------|---------|
| Personnel FT Pay          | 373,748 |
| Pay - Other               | 151,242 |
| Fringe benefits           | 95,123  |
| Overtime                  | 5,772   |

: Transportation Department Expenditures (in 1,000s) {#tbl-tdexp23}

Budget Overview FY23
:::

## FY22 Operations Budget

@tbl-tdbudget provides an overview of the FY22 budget for the Transportation Department broken out by operations and the source of the expenditure.

::: {#tbl-tdbudget layout-ncol="2"}
| Transportation Department      | 564,333 |
|--------------------------------|---------|
| Traffic engineering and design | 71,532  |
| Route construction             | 163,638 |
| Fleet                          | 50,404  |
| Bus operations                 | 150,000 |
| Management                     | 53,759  |
| Maintenance                    | 75,000  |

: Transportation Department Operations (in 1,000s) {#tbl-tdops}

| Transportation Department | 564,333 |
|---------------------------|---------|
| Personnel FT Pay          | 347,277 |
| Pay - Other               | 131,280 |
| Fringe benefits           | 77,834  |
| Overtime                  | 1,927   |

: Transportation Department Expenditures (in 1,000s) {tbl-tdexp}

Budget Overview FY22
:::
