---
title: "Police Department"
---

## Mission Statement

The mission of the Hopetopia Police Department is to protect the life and property of our
residents with an equal application of the law, to effectively enhance the safety of the public, and
to foster a positive relationship with the community.

## Recent News

::: callout-note
**10/3/2023** In conjunction with city-wide efforts to improve services, the Police Department has identified three performance goals that it will begin tracking and reporting publicly. 1. Shifting community policing from a unit-specific certification to a department-wide practice with full certification for all officers. 2. Tracking and increasing non-enforcement contact with public (with a goal of 5 interactions per officer per week). 3. Collecting 100 guns per month through the new gun buyback program.
:::

::: callout-note
**9/27/2023** The police chief has been focused on community policing efforts, using assigned and steady patrols who operate on a predicted schedule in pairs and have the same assigned beat for 6-month cycles. Recently, the investigations units unresolved crimes rate has increased by 30%, driven largely by poor clearance rates in the Southwest quadrant. Morale is generally low among your officers as some patrols feel their assigned beats are disproportionately more difficult than others. The department has also been struggling with community relations in the Southwest quadrant where multiple reports of officer misconduct have been verified by the Citizen Review Board.
:::

## Operations

### Who We Are

@tbl-pdstaff summarizes Police Department staffing by position and demographic characteristics of interest to the public.

|                 | Detectives | Sergeants | Officers | Captains | CRB | Total |
|-----------------|------------|-----------|----------|----------|-----|-------|
| White           | 141        | 705       | 2,073    | 41       | 33  | 2,993 |
| Non-white       | 25         | 124       | 829      | 0        | 29  | 1,007 |
| Male            | 145        | 746       | 1,865    | 33       | 25  | 2,815 |
| Female          | 21         | 83        | 1,036    | 8        | 37  | 1,185 |
| Non-resident    | 158        | 663       | 2,280    | 17       | 0   | 3,117 |
| College degree+ | 166        | 622       | 1,036    | 41       | 12  | 1,878 |
| Total           | 166        | 829       | 2,902    | 41       | 62  | 4,000 |

: Police Department Staffing Descriptive Statistics (FTE) {#tbl-pdstaff}

### How We're Doing

@tbl-pdperf provides the average performance on our tracked indicators for officers in each ward. The indicators are measured at the officer-level and then averaged by ward.

|                          | NW   | SW  | NE  | SE   |
|--------------------------|------|-----|-----|------|
| Percent of officers CP certified  | 25 | 10 | 15 | 20 |
| Avg. Number of Contacts (per week)  | 2   | 3.5 | .5 | 6.9   |
| Guns recovered through buyback (per month) | 15   | 25  | 65  | 23   |

: Police Department Performance Indicators by Ward {#tbl-pdperf}

## Current Operations Budget

@tbl-budgetpdall23 provides an overview of the FY23 budget proposed by the mayor and passed by the city council. The mayor's proposed budget maintains the FY22 allocation to the Department of Emergency Services in FY23. After weighing the proposed budgets, the Executive Director of the Department of Emergency Services granted the Police Chief's request for an additional 500,000 to double the budget for the Citizen Review Board. After meeting with neighborhood associations, business and non-profit leaders in Hopetopia, and attending City Council hearings, we have allocated the additional resources primarily to communications - focused on community policing training consistent with the mayor's goals. The bulk of the money will be allocated to hiring new personnel and procuring a contractor for conducting community policing professional development courses. See @tbl-pdallocate23 for details.

::: {#tbl-budgetpdall23 layout-ncol="3"}
| Policing and Corrections       | 961,782 |
|--------------------------------|---------|
| Police                         | 585,874 |
| Investigations and Forensics   | 25,113  |
| Corrections and Rehabilitation | 255,141 |
| Communications and Other       | 76,654  |
| Capital & Equipment            | 18,000  |
| Citizen Review Board           | 1,000   |

: Operations Budget for FY23 (in 1,000s) {#tbl-budgetpd23}

| Police           | 585,874 |
|------------------|---------|
| Capital          | 17,750  |
| Personnel FT Pay | 387,915 |
| Pay - Other      | 40,330  |
| Fringe benefits  | 88,163  |
| Overtime         | 51,716  |

: Police Budget Detail (in 1,000s) {#tbl-pddetail23}

| Police                   | 585,874 |
|--------------------------|---------|
| Patrol Services          | 256,219 |
| Investigations           | 136,373 |
| Administrative Support   | 24,043  |
| Professional Development | 50,145  |
| Internal Affairs         | 9,308   |
| Homeland Security        | 52,505  |
| Management               | 57,281  |

: Police Operations Allocations {#tbl-pdallocate23}

Budget Overview FY23
:::

## FY22 Operations Budget

@tbl-budgetpd outlines our budget for FY22 overall (in thousands) and @tbl-pddetail breaks out the details of the police budget by cost and @tbl-pdallocate breaks out the budget by operations. Our FY22 budget is currently in development.

::: {#tbl-budgetpdall layout-ncol="3"}
| Policing and Corrections       | 947,318 |
|--------------------------------|---------|
| Police                         | 572,163 |
| Investigations and Forensics   | 25,113  |
| Corrections and Rehabilitation | 255,141 |
| Communications and Other       | 76,404  |
| Capital & Equipment            | 18,000  |
| Citizen Review Board           | 500     |

: Operations Budget for FY22 (in 1,000s) {#tbl-budgetpd}

| Police           | 572,163 |
|------------------|---------|
| Capital          | 18,000  |
| Personnel FT Pay | 383,915 |
| Pay - Other      | 34,330  |
| Fringe benefits  | 86,663  |
| Overtime         | 49,252  |

: Police Budget Detail (in 1,000s) {#tbl-pddetail}

| Police                   | 572,163 |
|--------------------------|---------|
| Patrol Services          | 256,219 |
| Investigations           | 126,373 |
| Administrative Support   | 24,043  |
| Professional Development | 46,185  |
| Internal Affairs         | 9,308   |
| Homeland Security        | 52,505  |
| Management               | 57,531  |

: Police Operations Allocations {#tbl-pdallocate}

Budget Overview FY22
:::
