---
title: "Youth Social Services"
---

## Mission Statement

The Youth Social Services Department is devoted to ensuring the health, safety, and future success of Hopetopia’s at-risk and underserved youth. Through support services, educational programs, recreational activities, and job development initiatives, we work to promote the wellbeing of children and teens across the community and provide them the skills and resources needed to succeed as adults. The Department aims to enhance the livelihoods of Hopetopia’s youth through increased investment and manpower. Our programs not only improve the health and safety of our youth, but give them the skills and experience necessary to feel competent and confident in their future.

## Recent News

::: callout-note
**10/3/2023** In conjunction with city-wide efforts to improve services, Youth Social Services has identified three performance goals that it will begin tracking and reporting publicly. 1. Increase retention in our youth Recreational Sports Program by 10% (currently only 53% of eligible, participating youth return between seasons). 2. Reach 100% of Child Safety Unit calls within 24 hrs. 3. Increase participation in Future Readiness Program internships - which serves teens in foster care - by 10% (currently only 38% of eligible teens participate).
:::

::: callout-note
**9/27/2023** Youth Social Services provides foster care services and responds to and investigates reports of abuse (child protection services below). In addition, the youth services side of the department operates summer learning programs and early childhood education programs in coordination with the school district, an internship and jobs program for teens in the city, and recreational sport programs for low- and middle-income youth.
:::

## Operations

### Who We Are

@tbl-ysstaff provides an overview of the characteristics of our workforce by position.

|                 | Psychiatrists | Social workers | Central Office | Trainers | Total |
|------------|------------|------------|------------|------------|------------|
| White           | 142           | 1,780          | 712            | 178      | 2,812 |
| Non-white       | 36            | 356            | 178            | 178      | 748   |
| Male            | 53            | 534            | 356            | 89       | 1,032 |
| Female          | 125           | 1,602          | 534            | 267      | 2,528 |
| Non-resident    | 142           | 356            | 178            | 53       | 730   |
| College degree+ | 178           | 2,136          | 534            | 356      | 3,204 |
| Total           | 178           | 2,136          | 890            | 356      | 3,560 |

: Youth Social Services Staffing Descriptive Statistics (FTE) {#tbl-ysstaff}

### How We're Doing

@tbl-ysperf summarizes our current status on our new goals. The satisfaction grade is based on parent survey averages aggregated to the ward-level on scale of 0 to 100. Parents are prompted to grade the services they have received overall. Our child protection services investigate 2,400 reports of child abuse per year, with each ward ranging between 400 and 800 cases per year.

|                                                         | NW    | SW    | NE    | SE    |
|----------------------------------------|--------|--------|--------|--------|
| Inter-season retention rate (% eligible) | 88 | 30 | 22 | 72 |
| Percent of child safety calls contacted within 24hrs      | 62    | 18    | 45    | 73    |
| Percent participation in Internship Program      | 58    | 28    | 15    | 48    |

: Youth Social Services Performance Indicators by Ward {#tbl-ysperf}

## Current Operating Budget

@tbl-ysbudget23 provides an overview of our FY23 budget. The Mayor proposed an increase of 15,481,000. After meeting with the Parent Teacher Association (PTA), Hopetopia chapter of the Boys & Girls Club, and surveying the youth of Hopetopia's public schools, we have proposed an increased focus on summer jobs programs and child protection services. We've also provided a modest increase in funding for early education.

::: {#tbl-ysbudget22 layout-ncol="2"}
| Youth Social Services                        | 197,194 |
|----------------------------------------------|---------|
| Child protective services                    | 29,353  |
| Adoption and guardianship                    | 32,432  |
| Sports, recreation, and summer jobs programs | 2,069   |
| Child placement                              | 50,068  |
| Management                                   | 44,072  |
| Early education subsidy                      | 39,200  |

: Youth Social Services Operations (in 1,000s) {#tbl-ysops22}

| Youth Social Services | 197,194 |
|-----------------------|---------|
| Personnel FT Pay      | 116,822 |
| Pay - Other           | 47,272  |
| Fringe benefits       | 30,063  |
| Overtime              | 1,102   |

: Youth Social Services Expenditures (in 1,000s) {#tbl-ysexp22}

Budget Overview FY22
:::

## FY22 Operating Budget

@tbl-ysbudget provides an overview of the FY22 budget for Youth Social Services broken out by operations and the source of the expenditure.

::: {#tbl-ysbudget layout-ncol="2"}
| Youth Social Services                        | 181,713 |
|----------------------------------------------|---------|
| Child protective services                    | 24,819  |
| Adoption and guardianship                    | 29,875  |
| Sports, recreation, and summer jobs programs | 907     |
| Child placement                              | 45,754  |
| Management                                   | 43,385  |
| Early education subsidy                      | 36,973  |

: Youth Social Services Operations (in 1,000s) {#tbl-ysops}

| Youth Social Services | 181,713 |
|-----------------------|---------|
| Personnel FT Pay      | 111,822 |
| Pay - Other           | 42,272  |
| Fringe benefits       | 25,063  |
| Overtime              | 621     |

: Youth Social Services Expenditures (in 1,000s) {#tbl-ysexp}

Budget Overview FY22
:::
