---
title: "Housing and Planning Agency"
---

## Misson Statement

Our goal is to provide the highest standard of quality of life for the residents of our community by ensuring issues of health; safety, and property preservation are distributed fairly and equitably as a means of building inclusive and vibrant neighborhoods. Our department continually strives to develop strategies that enhance the economic well-being and growth of our community.

## Recent News

::: callout-note
**10/3/2023** In conjunction with city-wide efforts to improve services, the Housing and Planning Agency has identified three performance goals that it will begin tracking and reporting publicly. 1. A reduction in the number of grants that take longer than 3 months to process. 2. A reduction in the share of maintenance complaints that take longer than 2 weeks to process. 3. An increase in the ratio of eligible residents to available units that are affordable.
:::

::: callout-note
**9/27/2023** The head of the HPA has been prioritizing acquiring and rehabilitating abandoned properties in the NW quadrant for the last two years. The program prioritizes residential units and after rehabilitation, manages the units directly and offers both market rate and subsidized units. Recently, the market rate units have been experiencing vacancy rates as many other services and businesses are not convenient to the SW quadrant. Real Estate partners have also noted that the home ownership development programs are often insufficiently funded for SW residents given their economic need. As a result, most of the program helps first time home buyers in the SE and NW quadrants.
:::

## Operations

### Who We Are

@tbl-hpstaff provides an overview of the HPA workforce overall, by position, and broken out by characteristics of interest to the public.

|                 | Maintenance | Central office | Managers | Review Board | Total |
|-----------------|-------------|----------------|----------|--------------|-------|
| White           | 125         | 139            | 104      | 7            | 375   |
| Non-white       | 30          | 122            | 70       | 3            | 225   |
| Male            | 65          | 113            | 122      | 8            | 308   |
| Female          | 90          | 148            | 52       | 2            | 292   |
| Non-resident    | 66          | 104            | 122      | 0            | 292   |
| College degree+ | 55          | 217            | 174      | 10           | 456   |
| Total           | 155         | 261            | 174      | 10           | 600   |

: Housing and Planning Agency Staffing Descriptive Statistics (FTE) {#tbl-hpstaff}

### How We're Doing

@tbl-hpperf summarizes our preliminary performance assessment on our newly adopted performance metrics separately by ward. City-wide, we process 1,200 grants per year and 2,000 code enforcement calls per year.

|                                         | NW   | SW   | NE   | SE   |
|-----------------------------------------|------|------|------|------|
| Eligible resident:Affordable unit ratio | 80:1 | 25:1 | 35:1 | 60:1 |
| Number of grants \< 3 month delay       | 150  | 375  | 120  | 235  |
| Maintenance calls \< 2 week response    | 120  | 300  | 250  | 20   |

: Housing and Planning Agency Performance Indicators by Ward {#tbl-hpperf}

## Current Operations Budget

@tbl-hpbudget presents our operating budget for FY23. The mayor proposed and council passed a 91,857,000 increase in our operations budget. After meeting with housing and tenant advocates in the Southwest, Northeast, and Northwest quadrants, County officials, and real estate developers, we have drafted a set of investments that will improve housing stock quality and access to subsidized housing throughout the city. This fiscal year will focus on housing stock in the Southwest Ward.

::: {#tbl-hpbudget23 layout-ncol="2"}
| Housing and Planning Agency    | 233,000 |
|--------------------------------|---------|
| Planning                       | 22,000  |
| Housing subsidies              | 16,000  |
| Rehabilitation and Maintenance | 11,000  |
| Homeless services              | 9,000   |
| Vouchers                       | 79,000  |
| Supportive Housing             | 40,000  |
| Affordable Housing Families    | 33,000  |
| Affordable Housing Indiv.      | 10,000  |
| Rental Assistance              | 13,000  |

: Housing and Planning Operations (in 1,000s) {#tbl-hpops23}

| Housing and Planning Agency | 208,705 |
|-----------------------------|---------|
| Personnel FT Pay            | 130,480 |
| Pay - Other                 | 2,770   |
| Fringe benefits             | 55,226  |
| Overtime                    | 44,524  |

: Housing and Planning Expenditures (in 1,000s) {#tbl-hpdetail23}

Budget Overview FY23
:::

## FY22 Operations Budget

@tbl-hpbudget provides an overview of the FY22 budget for Housing and Planning broken out by operations and the source of the expenditure.

::: {#tbl-hpbudget layout-ncol="2"}
| Housing and Planning Agency    | 141,143 |
|--------------------------------|---------|
| Planning                       | 12,834  |
| Housing subsidies              | 8,547   |
| Rehabilitation and Maintenance | 1,024   |
| Homeless services              | 4,721   |
| Vouchers                       | 53,859  |
| Supportive Housing             | 25,017  |
| Affordable Housing Families    | 21,264  |
| Affordable Housing Indiv.      | 5,330   |
| Rental Assistance              | 8,547   |

: Housing and Planning Operations (in 1,000s) {#tbl-hpops}

| Housing and Planning Agency | 141,143 |
|-----------------------------|---------|
| Personnel FT Pay            | 86,856  |
| Pay - Other                 | 482     |
| Fringe benefits             | 19,467  |
| Overtime                    | 32,834  |

: Housing and Planning Expenditures (in 1,000s) {#tbl-hpdetail}

Budget Overview FY22
:::
