---
title: "General Services"
---

## Mission Statement

Hopetopia General Services will provide infrastructure and services to
enhance quality of life for all citizens in all wards of Hopetopia. On safely maintained roads,
bridges, and sidewalks, and through efficient infrastructure, we will foster community
development, enhance essential services and amenities, and ensure safe transportation throughout
the city.

## Recent News

::: callout-note
**10/3/2023** In conjunction with city-wide efforts to improve services, General Services has identified three performance goals that it will begin tracking and reporting publicly. 1. Reduce the number of pick-up delays. 2. Ensure traffic lights are functioning city-wide. 3. Increase park visits at city parks.
:::

::: callout-note
**9/27/2023** General Services provides a variety of basic infrastructural services, such as waste management (e.g., garbage and recycling collection and sorting), construction and maintenance of parks, enforcement of environmental regulations, and maintenance of government property (e.g., streets, sidewalks, streetlights, traffic lights and signs). Garbage collection workers have reported difficulty recruiting and retaining enough workers, leading to pickup delays in all four quadrants.
:::

## Operations

### Who We Are

@tbl-gsstaff provides an overview of our workforce by position and by demographic characteristics.

|                 | Regulators | Waste Collection | Maintenance | Management | Total |
|------------|------------|------------|------------|------------|------------|
| White           | 109        | 273              | 164         | 68         | 560   |
| Non-white       | 27         | 137              | 109         | 55         | 382   |
| Male            | 82         | 382              | 218         | 82         | 464   |
| Female          | 55         | 27               | 55          | 41         | 451   |
| Non-resident    | 41         | 191              | 218         | 68         | 396   |
| College degree+ | 137        | 41               | 55          | 123        | 846   |
| Total           | 137        | 410              | 273         | 123        | 942   |

: General Services Staffing Descriptive Statistics (FTE) {#tbl-gsstaff}

### How We're Doing

@tbl-gsperf summarizes our preliminary report of our performance on our newly adopted goals by ward. Respondents refers to respondents to our citizen survey fielded every six months.

|                                                     | NW  | SW  | NE  | SE  |
|-----------------------------------------------------|-----|-----|-----|-----|
| Number of pick-up delay complaints                  | 56  | 854 | 642 | 112 |
| Percent of traffic light outages fixed w/in 4 hours | 94  | 42  | 81  | 96  |
| Percent of respondents who visit parks weekly       | 87  | 32  | 25  | 98  |

: General Services Performance Indicators by Ward {#tbl-gsperf}

## Current Operations Budget

@tbl-gsbudget23 lays out our budget for the coming fiscal year. The Mayor proposed a 70,286,000 increase in our budget. After holding a public meeting in each of the wards, we have decided to focus our efforts on expanding the number of parks in the city - particularly in the less dense Southwest Ward - and improvements to the streetlights and traffic lights throughout the city.

::: {#tbl-gsbudget23 layout-ncol="2"}
| General Services                          | 384,625 |
|-------------------------------------------|---------|
| Snow removal                              | 9,129   |
| Fleet management                          | 40,649  |
| Parking enforcement                       | 40,814  |
| Waste Management                          | 105,574  |
| Management                                | 57,843  |
| Environmental regulations (water and air) | 59,449  |
| Parks and recreation                      | 48,524  |
| Additional Park Land Investment           | 15,343   |
| Street Light Safety Plan                  | 7,300   |

: General Services Operations (in 1,000s) {#tbl-gsops23}

| General Services | 384,625 |
|------------------|---------|
| Personnel FT Pay | 230,078 |
| Pay - Other      | 87,921  |
| Fringe benefits  | 54,203  |
| Overtime         | 12,723   |

: General Services Expenditures (in 1,000s) {#tbl-gsexp23}

Budget Overview FY23
:::

## FY22 Operating Budget

@tbl-gsbudget provides an overview of the FY22 budget for General Services broken out by operations and the source of the expenditure.

::: {#tbl-gsbudget layout-ncol="2"}
| General Services                          | 314,339 |
|-------------------------------------------|---------|
| Snow removal                              | 8,200   |
| Fleet management                          | 35,268  |
| Parking enforcement                       | 35,411  |
| Waste Management                          | 91,597  |
| Management                                | 50,185  |
| Environmental regulations (water and air) | 51,578  |
| Parks and recreation                      | 42,100  |

: General Services Operations (in 1,000s) {#tbl-gsops}

| General Services | 314,339 |
|------------------|---------|
| Personnel FT Pay | 193,437 |
| Pay - Other      | 73,124  |
| Fringe benefits  | 43,355  |
| Overtime         | 1,073   |

: General Services Expenditures (in 1,000s) {#tbl-gsexp}

Budget Overview FY22
:::
