---
title: "Fire Department"
---

## Mission Statement
Protecting the lives and property of Hopetopia citizens in a timely effective response to calls for services and enhancing the safety of our community through a collaborative public education and fire prevention program. 

## Recent News
:::{.callout-note}
**10/6/2022** In conjunction with city-wide efforts to improve services, the Fire Department has identified three performance goals that it will begin tracking and reporting publicly.
1. 90% of calls receive first response in under 7 mins. w/ at least 4 people and full force assembly within 11 mins.
2. Maintain effective minimum staffing of 5, 6 for identified high-volume areas, and 8 for dense urban areas.
3. 90% of calls processed within 60 seconds and 95% of calls processed within 106 seconds.
:::

:::{.callout-note}
**9/12/2022** Under the long-standing fire chief, morale is generally high, though the number of fires due to faulty wiring has been increasing. The fire chief believes inspection efforts for fire safety are underfunded and should be a priority.
:::

## Operations

### Who We Are
@tbl-fdstaff provides a count of the number of FTE staff by position and separately by demographic characteristics of interest to the public. 

|                 | Inspectors           | Investigators        | Central office       | Firefighters          | Station head        | Total              |
| --------------- | -------------------- | -------------------- | -------------------- | --------------------- | ------------------- | ------------------ |
| White           |                   84 |                   60 |                129   |               1,589   |                35   |            1,897   |
| Non-white       |                   15 |                   15 |                   70 |                   397 |                   5 |                502 |
| Male            |                   75 |                   65 |                   89 |               1,738   |                30   |            1,997   |
| Female          |                   25 |                   10 |                109   |                   248 |                10   |                402 |
| Non-resident    |                   89 |                   50 |                   99 |               1,242   |                10   |            1,490   |
| College degree+ |                   94 |                   75 |                149   |               1,316   |                40   |            1,674   |
| Total           |                100   |                   75 |                198   |               1,987   |                40   |            2,399   |

: Fire Department Staffing Descriptive Statistics (FTE) {#tbl-fdstaff}

### How We're Doing
@tbl-fdperf reports the average performance of stations in each Ward on our new performance indicators for the first half of 2022.

|                                           | NW | SW | NE | SE |
| ----------------------------------------- | -- | -- | -- | -- |
| Percent of responses w/in 4 mins          | 92 | 73 | 53 | 98 |
| Percent of full assembly w/in 8 mins      | 67 | 80 | 62 | 95 |
| Percent of responses w/ 5+ firefighters   | 89 | 54 | 75 | 92 |
| Percent of calls processed in <60 seconds | 98 | 80 | 77 | 97 |

: Fire Department Performance Indicators by Ward {#tbl-fdperf}

## Current Operations Budget
@tbl-budgetfdall22 provides an overview of the FY22 budget proposed by the mayor and passed by the city council. The mayor's proposed budget allocated a 23,959,600 budgetary increase to the Police and Fire departments. Although the Fire Department requested more resources, the mayor proposed a 10,000,000 increase in the operations budget. After a month of general public forums in each ward, we have identified timely inspections as a priority for the coming year. Accordingly, we have allocated an additional 8,000,000 to prevention and inspections and an additional 2,000,000 in professional development to hire and train additional fire safety inspectors throughout the city. @tbl-fdops22 summarizes out allocations for the coming year.

::: {#tbl-budgetfdall22 layout-ncol=2}
| Fire                 | 292,037 |
| -------------------- | -------------- |
| Operations | 181,889   |
| Administrative support  | 20,235  |
| Support Services       | 25,296   |
| Prevention and Inspections             | 32,408  |
| Professional Development            | 12,254  |
| Management | 19,955 |

: Operations Budget for FY22 (in 1,000s) {#tbl-fdops22}

| Fire                 | 292,037 |
| -------------------- | -------------- |
| Personnel FT Pay | 182,559 |
| Pay - Other | 963 |
| Fringe benefits | 40,900 |
| Overtime | 67,615 |

: Operations Budget for FY22 (in 1,000s) {#tbl-fddetail22}

Budget Overview
:::

## FY21 Operations Budget
@tbl-budgetfdall outlines our budget for FY21. @tbl-fdops summarizes the budget by operations and @tbl-fddetail summarizes the budget by type of expenditure. Our FY22 budget is current in development.

::: {#tbl-budgetfdall layout-ncol=2}
| Fire                 | 282,037 |
| -------------------- | -------------- |
| Operations | 181,889   |
| Administrative support  | 20,235  |
| Support Services       | 25,296   |
| Prevention and Inspections             | 24,408  |
| Professional Development            | 10,254  |
| Management | 19,955 |

: Operations Budget for FY21 (in 1,000s) {#tbl-fdops}

| Fire                 | 282,037 |
| -------------------- | -------------- |
| Personnel FT Pay | 176,559 |
| Pay - Other | 963 |
| Fringe benefits | 38,900 |
| Overtime | 65,615 |

: Operations Budget for FY21 (in 1,000s) {#tbl-fddetail}

Budget Overview
:::
