---
title: "Hopetopia Public Schools"
---

## Operations

### Who We Are

@tbl-psstaff summarizes the characteristics of our workforce by position and demographic characteristics.

|                 | Assistant Principals | Teachers | Support Staff | Principals | Total |
|------------|--------------|------------|------------|------------|------------|
| White           | 53                   | 3255     | 368           | 59         | 3735  |
| Non-white       | 13                   | 1184     | 184           | 53         | 1434  |
| Male            | 105                  | 1217     | 79            | 79         | 1480  |
| Female          | 53                   | 3222     | 473           | 33         | 3781  |
| Non-resident    | 99                   | 1032     | 520           | 53         | 1703  |
| College degree+ | 158                  | 4439     | 493           | 112        | 5202  |
| Total           | 158                  | 4439     | 552           | 112        | 5261  |

: Hopetopia Public Schools Staffing Descriptive Statistics (FTE) {#tbl-psstaff}

### How We're Doing

@tbl-psperf provides an overview of where we are on our goals in the current year. The data provides the average across schools in each ward of the city.

|                                          | NW   | SW   | NE   | SE   |
|------------------------------------------|------|------|------|------|
| Average teacher-student ratio            | 1:20 | 1:35 | 1:38 | 1:15 |
| Percent of teachers \>5 years experience | 73   | 46   | 42   | 88   |
| Percent of students graduating on-time   | 93   | 72   | 64   | 98   |

: Hopetopia Public Schools Performance Indicators by Ward {#tbl-psperf}

## Current Operations Budget

@tbl-psbudget25 summarizes the Hopetopia Public School District budget for FY25.

::: {#tbl-psbudget25 layout-ncol="2"}
| Hopetopia Public Schools                  | 2,030,549 |
|-------------------------------------------|-----------|
| Salaries (teachers, admin, paras, tutors) | 784,640   |
| Curriculum and staff development          | 120,413   |
| Contracted Services                       | 18,988    |
| Extracurricular & Community Events        | 104,670   |
| Transportation                            | 10,844    |
| Technology                                | 6,944     |
| Equipment                                 | 5,874     |
| Supplies                                  | 5,346     |
| Textbooks                                 | 4,807     |
| Utilities                                 | 3,987     |
| Student Services                          | 20,558    |
| Special Education Services                | 450,766   |
| Students who are EL's                     | 487,714   |

: Public Schools Operations (in 1,000s) {#tbl-psops25}

| Hopetopia Public Schools | 2,030,549 |
|--------------------------|-----------|
| Personnel FT Pay         | 1,341,433 |
| Pay - Other              | 393,690   |
| Fringe benefits          | 289,648   |
| Overtime                 | 5,778     |

: Public Schools Expenditures (in 1,000s) {#tbl-psexp25}

Budget Overview FY25
:::

--->
## FY24 Operations Budget

@tbl-psbudget provides an overview of the FY24 budget for Hopetopia Public Schools broken out by operations and the source of the expenditure.

::: {#tbl-psbudget layout-ncol="2"}
| Hopetopia Public Schools | 1,692,351 |
|--------------------------|-----------|
| Public schools           | 995,617   |
| Charter payments         | 500,675   |
| Transportation           | 104,959   |
| Community college        | 91,100    |

: Public Schools Operations (in 1,000s) {#tbl-psops}

| Hopetopia Public Schools | 1,692,351 |
|--------------------------|-----------|
| Personnel FT Pay         | 1,041,433 |
| Pay - Other              | 393,690   |
| Fringe benefits          | 233,418   |
| Overtime                 | 5,778     |

: Public Schools Expenditures (in 1,000s) {#tbl-psexp}

Budget Overview FY24
:::
