---
title: "Our Wards"
---

# Organization

The city of Hopetopia is a square grid that is roughly
14 miles by 16 miles with a population of 350,000 residents. The grid is
divided into four quadrants, with downtown and city hall resting in the center
of the city. Each quadrant has 4 roughly equally sized districts, each with a
representative on the city council (for a total of 16 council members) and each
district has 2-3 neighborhoods with linked economic and residential interests
with neighborhood associations who often lobby on their behalf. Broadly, the
city economy is propelled by 3 colleges in the city, one of which is a
community college and one of which is an elite Science, Technology, Engineering
and Mathematics (STEM) college, a few tech manufacturing and engineering firms,
and a robust service sector.

## Southwest quadrant

The Northwest quadrant of Hopetopia is highly populated, demographically mixed, but very low income section of the city beset
by problems and resource needs. The quadrant has widespread poverty, crumbling
roads in many neighborhoods, an increasing supply of abandoned and condemned
properties, and frequent complaints about the quality of the schools. Recently,
several businesses have left the quadrant, including 1 of the 2 primary
grocers, leaving residents with less access to food than other parts of the
city. The quadrant also contains two homeless shelters and three substance
abuse recovery centers.

## Northeast quadrant
The Northeast quadrant is a demographically and socioeconomically mixed neighborhood and houses a robust set of bars,
restaurants, and small to medium sized retailers. The schools in the quadrant
are average schools and the largest private employer in the region, Sid's
Software Co. (a tech company), is headquartered in the quadrant. The quadrant
is also home to the city's arena, which hosts events and the city's
professional basketball team. The quadrant is known for its high-rises and
density.

## Southeast quadrant

The southeast quadrant is primarily an upper-income
quadrant and less demographically mixed than the city as a whole. The schools
are well-funded and high-performing, the quadrant houses the area's large
university, and the quadrant contains a variety of very high-end retailers and
restaurants.

## Southwest quadrant
The Southwest quadrant is also very mixed income (from very wealthy to very poor) and very
demographically mixed. The schools are well-funded and high-performing, and
there are a range of businesses from smaller tech firms, a handful of mid-sized
manufacturing firms, and the community college and elite STEM college are in
the quadrant.